### ISSUE TITLE
Kikitan Translator Setup

### ISSUE THREAD

**Issue by That1PnkGuy** [YusufOzmen01/kikitan-translator#9]
Everytime I try to install the latest update, the software tell me that the software is open and to close it to continue. The software isn't open but continues to repeat. After clicking 'OK' to close it, it says "Failed to kill Kikitan Translator. Please close it first then try again." Once again, Kikitan isn't open.

**Comment by YusufOzmen01** [comment]
Try restarting your computer (You probably already tried). Otherwise, I don't really know why it could be doing that. You can download the zip file in the releases section and extract the files inside of Kikitan's installation folder and replace existing files. This will update Kikitan. Let me know how it goes.

Also, does this issue always happen when there is an update?

**Comment by That1PnkGuy** [comment]
This is my first update with Kikitan, I just recently got it. I tried resetting my PC a few times to see if that would help, but it showing the same issue.

**Comment by YusufOzmen01** [comment]
That is very weird, I've never seen this happen.

I'll look into this later. For now, can you update it manually like I said?

**Comment by That1PnkGuy** [comment]
As of right now, not possible. I deleted the software hoping it would help resolve it but it didn’t.

**Comment by YusufOzmen01** [comment]
Like I told you, use the zip, not the executable itself. The zip contains Kikitan's files. You can replace it with the old ones or extract it and use it in a folder like that.

Starting with the next update, I'll make the updates optional probably.

**Comment by YusufOzmen01** [comment]
Oh wait, I am stupid. The zip contains the setup.

Uninstalling and reinstalling manually should normally solve it. There might be a flag for the uninstaller to uninstall without checking if the app is running or not. I will check it whenever I can. I will reply to this issue once I find a solution

**Comment by YusufOzmen01** [comment]
Okay, can you delete Kikitan's files and try to remove it from the control panel? Since the files will be gone, control panel will assume it is deleted and remove it, so you can install the newest version. Just in case, I'm sending a build of Kikitan that has the checks disabled so you should be able to install it
[Kikitan Translator_1.2.1_x64-setup.nsis.zip](https://github.com/user-attachments/files/18166385/Kikitan.Translator_1.2.1_x64-setup.nsis.zip)

Let me know how it goes

**Comment by That1PnkGuy** [comment]
I finally got it to work! Thank you!

**Comment by YusufOzmen01** [comment]
I'm glad! If this issue happens again, contact me on Discord (sergiomarquina) so we can take a look at it more deeply. 

I'm closing the issue for now
